FROM ghcr.io/astral-sh/uv:python3.13-alpine

WORKDIR /app

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY pyproject.toml uv.lock ./
RUN uv sync --locked --no-install-project --no-dev

ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 5000
ENV FLASK_APP=app.py

CMD ["uv", "run", "flask", "run", "--host=0.0.0.0", "--port=5000", "--reload"]